<a href="https://colab.research.google.com/github/engm89/Pytorch-Journey/blob/main/numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
myList = [1,2,3]

In [3]:
type(myList)

list

In [6]:
arr = np.array(myList)
type(arr)

numpy.ndarray

In [7]:
myList = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

In [9]:
arr = np.array(myList)

In [10]:
arr.shape

(3, 4)

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])