In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'2.0.1'

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
type(arr)

numpy.ndarray

In [8]:
x = torch.from_numpy(arr)

In [9]:
type(x)

torch.Tensor

In [10]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [13]:
arr2d = np.arange(0.0, 12.0).reshape(4,3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [16]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [17]:
type(x2)

torch.Tensor

In [18]:
arr[0]=10

In [19]:
x

tensor([10,  2,  3,  4,  5], dtype=torch.int32)

In [21]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_tensor = torch.tensor(my_arr)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_tensor_2 = torch.from_numpy(my_arr)
my_tensor_2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [26]:
my_arr[0]=112

In [27]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [28]:
my_tensor_2

tensor([112,   1,   2,   3,   4,   5,   6,   7,   8,   9], dtype=torch.int32)

In [29]:
new_arr = np.array([1,2,3])

In [35]:
new_arr.dtype

dtype('int32')

In [31]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [33]:
torch.Tensor(new_arr).dtype

torch.float32

In [36]:
torch.empty(2,2)

tensor([[8.9082e-39, 6.9796e-39],
        [9.0919e-39, 9.9184e-39]])

In [38]:
torch.zeros(3,3, dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [39]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [41]:
torch.arange(1,10).reshape(3,3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [42]:
torch.linspace(0,18,12)

tensor([ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818,  9.8182, 11.4545,
        13.0909, 14.7273, 16.3636, 18.0000])

In [43]:
my_tensor = torch.tensor([1,2,3])

In [44]:
my_tensor.type(torch.int16)

tensor([1, 2, 3], dtype=torch.int16)

In [45]:
my_tensor

tensor([1, 2, 3])

In [46]:
torch.rand(3,3)

tensor([[0.2136, 0.7056, 0.7654],
        [0.6586, 0.0345, 0.2107],
        [0.9083, 0.7647, 0.3814]])

In [47]:
torch.randn(4,4)

tensor([[-1.2844,  1.1016,  0.0409, -1.0917],
        [ 0.1724,  0.2683, -0.9105, -0.6041],
        [ 0.1807, -0.7347,  0.8367, -0.0762],
        [ 0.4865,  0.0460, -1.6295,  0.4555]])

In [50]:
torch.randint(low=1, high=10, size=(5,5))

tensor([[9, 8, 9, 8, 4],
        [2, 3, 1, 2, 6],
        [6, 2, 4, 4, 4],
        [6, 8, 2, 1, 5],
        [5, 1, 9, 9, 3]])

In [52]:
torch.manual_seed(42)

torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])